version: '3.9'
# name: grafana-api-test-dashboard
services:
  # Database (Postgres) service
  postgres:
    image: postgres:latest
    container_name: db
    # environment:
    #   - PGUSER=grafana
    env_file:
      - ./src/.env
    ports:
      - 6432:5432
    shm_size: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    restart: always

  # The grafana dashboard
  grafana-dashboard:
    depends_on:
      - postgres
    image: grafana/grafana:latest
    container_name: dashboard
    ports:
      - 3000:3000
    networks:
      - default

  # Python API service
  grafana-fastapi-server:
    depends_on:
      - postgres
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    restart: always
    # entrypoint: sh start.sh
    networks:
      - default

  # Initialization & Scheduler
  scheduler:
    depends_on:
      - grafana-fastapi-server
    container_name: scheduler
    build:
      context: .
    working_dir: /src
    networks:
      - default
    command: ["sh", "start.sh"]
