version: '3.9'
# name: grafana-api-test-dashboard
services:
  # Database (Postgres) service
  db:
    image: postgres:14.1-alpine
    container_name: grafana-dash-db
    environment:
      - PGUSER=postgres
    env_file:
      - ./src/.env
    ports:
      - 2345:5432
    shm_size: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    restart: always
  # Python API tester
  tester:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: always
    networks:
      - default
# alembic revision -m "migration-script" --autogenerate && alembic upgrade head
