version: '3.9'
# name: grafana-api-test-dashboard
services:
  # Database (Postgres) service
  postgres:
    image: postgres:latest
    container_name: grafana-dash-db
    environment:
      - PGUSER=grafana
    env_file:
      - ./src/.env
    ports:
      - 6432:5432
    shm_size: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    restart: always

  # Python API service
  grafana-fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    depends_on:
      - postgres
    ports:
      - 8000:8000
    restart: always
    networks:
      - default
