version: '3.9'
# name: grafana-api-test-dashboard
services:
  # Database (Postgres) service
  postgres:
    image: postgres:latest
    container_name: grafana-dash-db
    environment:
      - PGUSER=grafana
    env_file:
      - ./src/.env
    ports:
      - 6432:5432
    shm_size: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default
    restart: always

  # Python API service
  grafana-fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    depends_on:
      - postgres
    # volumes:
    #   - ./src:/api
    ports:
      - 8000:8000
    restart: always
    networks:
      - default

  # The grafana dashboard
  grafana-dashboard:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - default

  # # Initialize grafana inside the container
  grafana-init:
    build:
      context: .
    working_dir: /src
    depends_on:
      - grafana-fastapi-server
      - grafana-dashboard
    networks:
      - default
    command: ["sh", "grafana-init.sh"]
