{
 "title": "API Test Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Count per version",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(version), version FROM api GROUP BY version LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average response time per version",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n\tversion, AVG(elapsed)\nFROM\n\tapi\nINNER JOIN\n\tresponse ON response.api_id = api.id\nGROUP BY\n  version"
    }
   ]
  },
  {
   "title": "Average response time per category",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcategory, AVG(elapsed)\nFROM\n\tapi\nINNER JOIN\n\tresponse ON response.api_id = api.id\nGROUP BY\n  category"
    }
   ]
  },
  {
   "title": "Categories of Apis",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  category, COUNT(category)\nFROM\n  api\nGROUP BY\n  category"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "path": "img" }
   ]
  }
 ]
}